import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import ToolBar from "../components/toolbar";
import MenuContextProvider from "../Context/menuContext";
import styles from "../styles/Home.module.css";
import Companies from "../components/companys";

const Home: NextPage = () => {
  const divMenu = React.useRef<HTMLDivElement>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Epilogue:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <>
        <MenuContextProvider>
          <nav>
            <ToolBar />
          </nav>
        </MenuContextProvider>
        <main className={styles.main}>
          <span className={styles.background} />
          <div className={styles.mainInfo}>
            <p>Make remote work</p>
            <h6>
              Get your team in sync, no matter your locantion. Streamline
              processes, create team rituals, and watch productivity soar.
            </h6>
            <button>Learn more</button>
            <Companies />
          </div>
        </main>
      </>
    </div>
  );
};

export default Home;
